Second batch of PR review comments addressed
edgexfoundry-holding/rfid-llrp-inventory-service pull request #20
Opened 2021-05-07 23:25 UTC by ajcasagrande

https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r595519578
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r595523551
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r595524138
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r595525260
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r595572991
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r595575088
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#pullrequestreview-613781892
https://github.com/edgexfoundry-holding/rfid-llrp-inventory-service/pull/18#discussion_r595588978

Signed-off-by: Anthony Casagrande <anthony.j.casagrande@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Are there any new imports or modules? If so, what are they used for and why?
No

## Are there any specific instructions or things that should be known prior to reviewing?
No

## Other information
N/A

2021-05-11 19:01 UTC, lenny-intel requested changes

2021-05-11 21:46 UTC, ajcasagrande commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!-- If your build fails due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/app-functions-sdk-go/blob/master/.github/CONTRIBUT
ah, ok

2021-05-11 21:48 UTC, ajcasagrande commented on internal/llrp/util_test.go
> +package llrp
They never existed in the first place. This was my way of noting that there probably should be some.

2021-05-11 22:13 UTC, lenny-intel commented on internal/logutil/logwrap.go
> +type LogWrap struct {
Yep, agree.

2021-05-12 18:12 UTC, lenny-intel commented on internal/llrp/util_test.go
> +package llrp
So are unit tests planned for another PR? i.e. we can merge this one?

2021-05-12 21:26 UTC, lenny-intel approved these changes
LGTM

2021-05-12 21:26 UTC, merged